# Generated by Django 5.0.2 on 2024-02-15 11:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exams',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recruitment_teams',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('dept_name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=50)),
                ('contact', models.IntegerField()),
                ('address', models.TextField(blank=True, null=True)),
                ('experience', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('questions', models.TextField()),
                ('options', models.JSONField(default=dict)),
                ('true_option', models.IntegerField()),
                ('exam_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project1.exams')),
            ],
        ),
        migrations.AddField(
            model_name='exams',
            name='dept_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project1.recruitment_teams'),
        ),
        migrations.CreateModel(
            name='Attemps_log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_ans', models.IntegerField()),
                ('is_ans_true', models.BooleanField(default=None)),
                ('que_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project1.questions')),
                ('stu_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project1.students')),
            ],
        ),
        migrations.CreateModel(
            name='Students_Results',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.IntegerField()),
                ('exam_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project1.exams')),
                ('stu_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='project1.students')),
            ],
        ),
    ]
