# Generated by Django 5.0.2 on 2024-02-16 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='options',
            field=models.JSONField(default={'1': '', '2': '', '3': '', '4': ''}),
        ),
    ]
