# Generated by Django 5.0.2 on 2024-02-29 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project1', '0002_alter_attemps_log_is_ans_true'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attemps_log',
            name='is_ans_true',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
