# Generated by Django 5.0.2 on 2024-02-29 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project1', '0003_alter_attemps_log_is_ans_true'),
    ]

    operations = [
        migrations.AddField(
            model_name='attemps_log',
            name='attempted',
            field=models.BooleanField(default=False),
        ),
    ]
