# Generated by Django 5.0.2 on 2024-03-01 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project1', '0005_remove_students_address_remove_students_experience'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attemps_log',
            unique_together={('que_id', 'stu_id')},
        ),
    ]
